name: deploy-prod

on:
  push:
    branches:
    - main



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init --input=false

    - name: Terraform Plan
      run: terraform plan

