name: deploy-staging

on:
  pull_request:
    branches:
    - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_BIN_API_KEY : ${{ secrets.TF_VAR_BIN_API_KEY }}
      TF_VAR_BIN_API_SECRET : ${{ secrets.TF_VAR_BIN_API_SECRET }}
      TF_VAR_COSMOBOT_STAGING : ${{ vars.TF_VAR_COSMOBOT_STAGING }}
      TF_VAR_COSMOBOT_FROM_LAMBDA : ${{ vars.TF_VAR_COSMOBOT_FROM_LAMBDA }}
      TF_VAR_COSMOBOT_DISCORD_HOOK_URL : ${{ secrets.TF_VAR_COSMOBOT_DISCORD_HOOK_URL }}
      TF_VAR_COSMOBOT_DISCORD_ROLE : ${{ vars.TF_VAR_COSMOBOT_DISCORD_ROLE }}

    steps:
    - uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      run: terraform init --input=false

    - name: Terraform validation
      run: terraform validate

    - name: Terraform import cosmoagent lambda function
      run: terraform import --input=false aws_lambda_function.cosmoagent_lambda cosmoagent_lambda_staging
      continue-on-error: true

    - name: Terraform import cosmoagent lambda trigger
      run: terraform import --input=false aws_lambda_permission.allow_eventbridge_cosmoagent cosmoagent_lambda_staging/event_bridge_trigger_cosmoagent
      continue-on-error: true

    - name: Terraform import cosmobot lambda function
      run: terraform import --input=false aws_lambda_function.cosmobot_lambda cosmobot_lambda_staging
      continue-on-error: true

    - name: Terraform import cosmobot lambda trigger
      run: terraform import --input=false aws_lambda_permission.allow_eventbridge_cosmobot cosmobot_lambda_staging/event_bridge_trigger_cosmobot
      continue-on-error: true

    - name: Terraform apply
      run: terraform apply --auto-approve --input=false

    - name: Output the branch name
      run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)

    - name: Set env.BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

    - name: Is staging?
      if: env.BRANCH == 'staging'
      run: echo "This is 'staging' branch"

    - name: Is staging?
      if: ${{ github.head_ref == 'staging' }}
      run: echo "This is 'last staging debug' branch"