name: deploy-prod

on:
  push:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_BIN_API_KEY : ${{ secrets.TF_VAR_BIN_API_KEY }}
  TF_VAR_BIN_API_SECRET : ${{ secrets.TF_VAR_BIN_API_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      run: terraform init --input=false

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform validation
      run: terraform validate

    - name: Terraform import cosmoagent lambda function
      run: terraform import aws_lambda_function.cosmoagent_lambda cosmoagent_lambda
      continue-on-error: true

    - name: Terraform import cosmoagent lambda trigger
      run: terraform import aws_lambda_permission.allow_eventbridge_cosmoagent cosmoagent_lambda/event-bridge-trigger-cosmoagent
      continue-on-error: true

    - name: Terraform apply
      env:
        TF_VAR_COSMOBOT_DEBUG : ${{ env.TF_VAR_COSMOBOT_DEBUG }}
        TF_VAR_COSMOBOT_FROM_LAMBDA : ${{ env.TF_VAR_COSMOBOT_FROM_LAMBDA }}
      run: terraform apply --auto-approve
