name: tests

on:
  push:
    branches:
    - "**"
    - "!main"

env:
  DEBUG: ${{ env.TF_VAR_COSMOBOT_DEBUG }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

     - name: "Say DEBUG!"
        run: echo "$DEBUG"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
