name: tests

on:
  push:
    branches:
    - "**"
    - "!main"
    - "!staging"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Output the branch name
      run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)

    - name: Set env.BRANCH
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

    - name: Is staging?
      if: env.BRANCH == 'staging'
      run: echo "This is 'staging' branch"

    - name: Is staging?
      if: ${{ github.head_ref == 'staging' }}
      run: echo "This is 'last staging debug' branch"